[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(name)s:%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S
addopts = --benchmark-autosave --benchmark-save-data --benchmark-min-rounds=30
